api-version: 1.20

name: ${project.name}
version: ${project.version}
description: '${project.description}'

main: dev.imprex.shieldedimpact.plugin.ShieldedImpactPlugin

author: NgLoader

commands:
  shield:

permissions:
  shieldedimpact.*:
    default: false
    description: Access to all of Zero Inventory Problems features